### PR TITLE
feat: Add wireguard support

### PR DESCRIPTION
**Pull request by RoiArthurB**
Following wireguard custom kernel compatibility developped by Wireguard for kernel 3.10-5.5 with their tool here : https://github.com/WireGuard/wireguard-linux-compat

### CODE REVIEW

**Comment by FakeShell** [comment]
@RoiArthurB Hi
Thanks for taking your time to backport wireguard (as i assume it is a fairly useful component nowadays) and your contributions to the project.

Have you tested this to be working on droidian with the latest commit and latest package applied? If so, is it confirmed to be working? Its quite a big commit so it has the possibility of breaking functionality. If it is confirmed working please provide a boot image that has been built and confirmed to be working.
Thank you

**Comment by RoiArthurB** [comment]
Hi,

I haven't built it and test it yet as my op3 is currently on the default droidian image, I'm planning to found so time this weekend to try this all.

However, this should work flawlessly as I just applied a well tested patch from wireguard specially for the purpose of bringing wireguard to older custom patch :)

So I'll probably test it myself in the following days, but I don't see why it would create any issue (just added an independant component) nor why it wouldn't work 😉

**Comment by FakeShell** [comment]
@RoiArthurB Hi,

even if wireguard has been added separately from all other modules, you have to consider that its an old android kernel so anything can happen. it cannot be merged without proper testing.
please report back after testing
thank you

**Comment by RoiArthurB** [comment]
Hi @FakeShell,

Thanks to enforced such good code quality in this project. Indeed my PR wasn't working properly (missing a little hacky patch as we're on an Android kernel and not a pure Linux one).

<details>
 <summary>Show successful compilation log</summary>

```
$ mka halium-boot
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=lineage_oneplus3
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.1.29-1-lts-x86_64-Ubuntu-20.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/root/halium/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8996 hardware/qcom/display-caf/msm8996 hardware/qcom/media-caf/msm8996
============================================
ninja: no work to do.
ninja: no work to do.
No need to regenerate ninja file
No need to regenerate ninja file
[ 28% 2/7] Building Kernel Config
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --savedefconfig=defconfig Kconfig
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
[ 42% 3/7] Building Kernel
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CHK     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  CC      kernel/sys.o
  CC      drivers/base/firmware_class.o
  LD      drivers/base/built-in.o
  CC      kernel/trace/trace.o
  CC      kernel/module.o
  GZIP    kernel/config_data.gz
  LD      kernel/trace/built-in.o
  CHK     kernel/config_data.h
  LD      kernel/built-in.o
  LD      drivers/built-in.o
  LINK    vmlinux
  LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
  DTC     arch/arm64/boot/dts/qcom/msm8996-v3-pmi8996-mtp_15801.dtb
  DTC     arch/arm64/boot/dts/qcom/msm8996pro-pmi8996-mtp_15811.dtb
  GZIP    arch/arm64/boot/Image.gz
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
Building DTBs
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
Building Kernel Modules
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CC [M]  net/wireguard/main.o
  CC [M]  net/wireguard/noise.o
  CC [M]  net/wireguard/device.o
  CC [M]  net/wireguard/peer.o
  CC [M]  net/wireguard/timers.o
  CC [M]  net/wireguard/queueing.o
  CC [M]  net/wireguard/send.o
  CC [M]  net/wireguard/receive.o
  CC [M]  net/wireguard/socket.o
  CC [M]  net/wireguard/peerlookup.o
  CC [M]  net/wireguard/allowedips.o
  CC [M]  net/wireguard/ratelimiter.o
  CC [M]  net/wireguard/cookie.o
  CC [M]  net/wireguard/netlink.o
  CC [M]  net/wireguard/crypto/zinc/chacha20/chacha20.o
  CC [M]  net/wireguard/crypto/zinc/poly1305/poly1305.o
  CC [M]  net/wireguard/crypto/zinc/chacha20poly1305.o
  CC [M]  net/wireguard/crypto/zinc/blake2s/blake2s.o
  CC [M]  net/wireguard/crypto/zinc/curve25519/curve25519.o
  CC [M]  net/wireguard/compat/siphash/siphash.o
  CC [M]  net/wireguard/compat/dst_cache/dst_cache.o
  LD [M]  net/wireguard/wireguard.o
  Building modules, stage 2.
  MODPOST 5 modules
  CC      crypto/ansi_cprng.mod.o
  CC      drivers/video/backlight/backlight.mod.o
  CC      drivers/video/backlight/generic_bl.mod.o
  CC      drivers/video/backlight/lcd.mod.o
  CC      net/wireguard/wireguard.mod.o
  LD [M]  net/wireguard/wireguard.ko
  LD [M]  drivers/video/backlight/lcd.ko
  LD [M]  crypto/ansi_cprng.ko
  LD [M]  drivers/video/backlight/backlight.ko
  LD [M]  drivers/video/backlight/generic_bl.ko
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
[ 57% 4/7] build INSTALLED_KERNEL_MODULES
Installing Kernel Modules
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  INSTALL crypto/ansi_cprng.ko
  INSTALL drivers/video/backlight/backlight.ko
  INSTALL drivers/video/backlight/generic_bl.ko
  INSTALL drivers/video/backlight/lcd.ko
  INSTALL net/wireguard/wireguard.ko
  DEPMOD  3.18.121-g1515045d-dirty
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
depmod: WARNING: could not open /root/halium/out/target/product/oneplus3/obj/PACKAGING/depmod_vendor_intermediates/lib/modules/0.0/modules.order: No such file or directory
depmod: WARNING: could not open /root/halium/out/target/product/oneplus3/obj/PACKAGING/depmod_vendor_intermediates/lib/modules/0.0/modules.builtin: No such file or directory
[100% 7/7] Install: /root/halium/out/target/product/oneplus3/halium-boot.img

#### build completed successfully (01:19 (mm:ss)) ####
```

</details>

Now the `halium-boot.img` is compiling well. I haven't got the time to test it yet (probably gonna do tomorrow), but [you can found it here](https://e.pcloud.link/publink/show?code=kZBP0uZcVClq73sUYSWy4dxUK6ASf4yVGvV) :) 

---

EDIT: An infinite thanks to @Bettehem to did more than helping me understand how to compile droidian :pray:

**Comment by RoiArthurB** [comment]
Hi @FakeShell and @Bettehem ! 

So I did flash my new `halium-boot.img` on my OP3, the new kernel is in use (can see with the bumped kernel version) 

```
droidian@lineageoneplus3:~$ neofetch 
        #####           droidian@lineageoneplus3 
       #######          ------------------------ 
       ##O#O##          OS: Droidian bookworm aarch64 
       #######          Host: Qualcomm Technologies, Inc. MSM 8996 v3 + PMI8996 MTP 
     ###########        Kernel: 3.18.121-g1515045d-dirty 
    #############       Uptime: 22 mins 
   ###############      Packages: 1294 (dpkg) 
   ################     Shell: bash 5.2.15 
  #################     Terminal: /dev/pts/1 
#####################   CPU: Qualcomm MSM8996 (3) @ 1.190GHz 
#####################   Memory: 1292MiB / 5735MiB 
  #################
```

But the add of WireGuard didn't work as no kernel modules have been added nor are available in the build...

```
droidian@lineageoneplus3:~$ sudo lsmod
Module                  Size  Used by
droidian@lineageoneplus3:~$
droidian@lineageoneplus3:~$ sudo tree -a /lib/modules/3.18.120-Halium-g814cbca2-dirty/ 
/lib/modules/3.18.120-Halium-g814cbca2-dirty/
`-- build

2 directories, 0 files
```

I can't say whether I'm missing something from the kernel compilation or regarding the android img, but my pr isn't helping anything so far :/ 

BTW, I tried to install wireguard but it fails probably because of this kernel's module missing...

```
droidian@lineageoneplus3:~$ sudo systemctl enable --now wg-quick@wg-client0.service
Job for wg-quick@wg-client0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg-client0.service" and "journalctl -xeu wg-quick@wg-client0.service" for details.

droidian@lineageoneplus3:~$ systemctl status wg-quick@wg-client0.service
× wg-quick@wg-client0.service - WireGuard via wg-quick(8) for wg/client0
     Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-05-21 11:14:15 +07; 9s ago
       Docs: man:wg-quick(8)
             man:wg(8)
             https://www.wireguard.com/
             https://www.wireguard.com/quickstart/
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
    Process: 10102 ExecStart=/usr/bin/wg-quick up wg-client0 (code=exited, status=1/FAILURE)
   Main PID: 10102 (code=exited, status=1/FAILURE)
```

**Comment by FakeShell** [comment]
@RoiArthurB Hello

try building wireguard inline within the kernel instead of having it as a module. in case of any defconfig modifications, it should be CONFIG_WIREGUARD=y or whatever the configuration name is instead of CONFIG_WIREGUARD=m
Same concept applies to menuconfig. It should be set to (*) instead of (M)

As of now we cannot use modules on Droidian on the oneplus-3. this behavior will soon be fixed (after we get mapper and LVM working) but for now everything should be built into the kernel itself instead of having it as a module

I appreciate the effort you're putting it. feel free to ask if you have any other questions

**Comment by RoiArthurB** [comment]
@FakeShell @Bettehem I'm unsure which defconfig is used by Droidian in our case. I could update them all to add CONFIG_WIREGUARD inside, but I think it would be cleaner to only add it in the needed file :)

**Comment by FakeShell** [comment]
@RoiArthurB Hey

It should be lineageos_oneplus3_defconfig in arch/arm64/configs

**Comment by RoiArthurB** [comment]
My last commit should implement wireguard inline the kernel and not as a module anymore 

<details>
 <summary>Show successful compilation log</summary>

```
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=lineage_oneplus3
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.1.29-1-lts-x86_64-Ubuntu-20.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/root/halium/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8996 hardware/qcom/display-caf/msm8996 hardware/qcom/media-caf/msm8996
============================================
ninja: no work to do.
ninja: no work to do.
No need to regenerate ninja file
No need to regenerate ninja file
[ 28% 2/7] Building Kernel Config
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --savedefconfig=defconfig Kconfig
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
[ 42% 3/7] Building Kernel
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
  CC      net/wireguard/ratelimiter.o
  LD      net/wireguard/wireguard.o
  LD      net/wireguard/built-in.o
  LD      net/built-in.o
  LINK    vmlinux
  LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
  DTC     arch/arm64/boot/dts/qcom/msm8996-v3-pmi8996-mtp_15801.dtb
  DTC     arch/arm64/boot/dts/qcom/msm8996pro-pmi8996-mtp_15811.dtb
  GZIP    arch/arm64/boot/Image.gz
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
Building DTBs
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
Building Kernel Modules
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /root/halium/kernel/oneplus/msm8996 as source for kernel
  CALL    /root/halium/kernel/oneplus/msm8996/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CC [M]  crypto/ansi_cprng.o
  CC [M]  drivers/video/backlight/lcd.o
  CC [M]  drivers/video/backlight/backlight.o
  CC [M]  drivers/video/backlight/generic_bl.o
  Building modules, stage 2.
  MODPOST 4 modules
  CC      crypto/ansi_cprng.mod.o
  CC      drivers/video/backlight/backlight.mod.o
  CC      drivers/video/backlight/generic_bl.mod.o
  CC      drivers/video/backlight/lcd.mod.o
  LD [M]  drivers/video/backlight/backlight.ko
  LD [M]  drivers/video/backlight/lcd.ko
  LD [M]  crypto/ansi_cprng.ko
  LD [M]  drivers/video/backlight/generic_bl.ko
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
[ 57% 4/7] build INSTALLED_KERNEL_MODULES
Installing Kernel Modules
make: Entering directory '/root/halium/kernel/oneplus/msm8996'
make[1]: Entering directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
  INSTALL crypto/ansi_cprng.ko
  INSTALL drivers/video/backlight/backlight.ko
  INSTALL drivers/video/backlight/generic_bl.ko
  INSTALL drivers/video/backlight/lcd.ko
  DEPMOD  3.18.121-g1515045d-dirty
make[1]: Leaving directory '/root/halium/out/target/product/oneplus3/obj/KERNEL_OBJ'
make: Leaving directory '/root/halium/kernel/oneplus/msm8996'
depmod: WARNING: could not open /root/halium/out/target/product/oneplus3/obj/PACKAGING/depmod_vendor_intermediates/lib/modules/0.0/modules.order: No such file or directory
depmod: WARNING: could not open /root/halium/out/target/product/oneplus3/obj/PACKAGING/depmod_vendor_intermediates/lib/modules/0.0/modules.builtin: No such file or directory
[100% 7/7] Install: /root/halium/out/target/product/oneplus3/halium-boot.img

#### build completed successfully (53 seconds) ####
```

</details>

I'll test it tonight and you can [found the kernel/img here](https://e.pcloud.link/publink/show?code=kZEsFuZCgyIIiq37J5VWNMM7oKhnzfVl0j7) :)

**Comment by RoiArthurB** [comment]
Hey @FakeShell @Bettehem ! I'm thrilled to announce you that this PR is ready to be pulled and is actually working fine ! :smile: :partying_face: 

droidianwireguard

The only minor issue that I faced (not even sure it comes from this PR) is that I needed to reconnect manually to my wifi on first reboot (maybe because I had the new VPN interface active? Maybe because it did modify something on nmconnect files -not as far as I watch-? Maybe I'll be the only one to face this small issue?)

Feel free to merge/try it  when you'll want to :) Also, feel free to ask me to test some more stuff if needed

**Comment by FakeShell** [comment]
@RoiArthurB Hey

Looks good to me. Don't increment the kernel sublevel set it back to 120. Also please set the localversion in that defconfig to oneplus-oneplus3
You can definitely sqaush all of your commits as well to make everything cleaner

**Comment by RoiArthurB** [comment]
Hi @FakeShell ,

I pushed commit fixing the kernel's sublevel and changing the `CONFIG_LOCALVERSION` (not exactly sure why it should be done in this PR, but ok :shrug: ) :) 

Also, I'll let you squash them with the Github's option to `Squash and Merge`

image

**Comment by FakeShell** [comment]
@RoiArthurB LGTM 👍

**Pull request merged**
